source "https://rubygems.org"

gem "sinatra", "~>2.0.5"
github 'sinatra/sinatra' do
  gem 'sinatra-contrib'
end
gem "erubis"
gem 'pry-byebug'

group :test do
  gem 'minitest', '~>5.11.3'
  gem 'capybara', '~>3.13.2'
end
