require 'rake/testtask'

task :basics_one_task do
  Rake::TestTask.new('classes_and_objects_one') do |t|
    t.libs << 'test'
    t.test_files = FileList["test/basics/classes_and_objects_one/*_test.rb"]
    t.verbose = true
    t.warning = true
  end
end

task :basics_one do
  Rake::Task['basics_one_task'].invoke
end