require 'rake/testtask'

task :board_test_task do
  Rake::TestTask.new('board') do |t|
    t.libs << "test/board"
    t.test_files = FileList["test/board/*_test.rb"]
    t.warning = false
    t.verbose = false
  end
end

task :board_test do
  RakeTask["board_test_task"].invoke
end