source "https://rubygems.org"

gem 'sinatra', '~>2.0.5'
github 'sinatra/sinatra' do
  gem 'sinatra-contrib'
end
gem 'erubis', '~>2.7.0'
gem 'pry-byebug', '~>3.7.0'

group :test do
  gem 'minitest', '~>5.11.3'
  gem 'capybara', '~>3.15.0'
  gem 'rack-test', '~>1.1.0'
end
