#! /usr/bin/env ruby
require 'pry-byebug'
require_relative './cli_constants'
require_relative './table_format'
require_relative './cli'
require_relative './expense_data'

cli = Cli.new(ARGV)
tf = TableFormat.new
expenses = ExpenseData.new(cli, tf)

if cli.command.nil?
  puts CliConstants::HELP
elsif !cli.valid_command?
  puts CliConstants::INFO_MSG
else
  expenses.send(cli.command.to_sym)
end
