CREATE TABLE expenses (
	id SERIAL PRIMARY KEY,
	amount DECIMAL(6, 2) NOT NULL CHECK (amount >= 0.01),
	memo TEXT NOT NULL,
	created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
);