CREATE TABLE list (
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE todo (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	completed BOOLEAN NOT NULL DEFAULT FALSE,
	list_id INTEGER NOT NULL REFERENCES list (id)
);