source "https://rubygems.org"

ruby "2.6.3"

gem "sinatra", "~>2.0.5"
gem "sinatra-contrib", "~>2.0.5"
gem "erubis", "~>2.7.0"

group :development do
  gem "pry-byebug", "~>3.7.0"
  gem "rubocop", "~>0.73.0"
end

group :test do
  gem "minitest", "~>5.11.3"
  gem "capybara", "~>3.26.0"
  gem "rack-test", "~>1.1.0"
  gem "rack_session_access", "~>0.2.0"
end

group :production do
  gem "puma", "~>4.0.1"
end
