OneLineMessages:
  FirstNumberMessage: "What's the first number?"
  SecondNumberMessage: "What's the second number?"
  RepeatCalculationMessage: "Do you want to perform another calculation?  (Y to calculate again)"
MultiLineMessages:
  OperatorPrompt: |
      What operation would you like to perform? (enter a number)
      1) Add
      2) Subtract
      3) Multiply
      4) Divide