require 'rake/testtask'

task :easy_one_task do
  Rake::TestTask.new('easy_one') do |t|
  t.libs << "easy/one/test"
  t.test_files = FileList['easy/one/test/*_test.rb']
  t.verbose = false
  t.warning = false
  end
end

task :easy_two_task do
  Rake::TestTask.new('easy_two') do |t|
    t.libs << "easy/two/test"
    t.test_files = FileList['easy/two/test/*_test.rb']
    t.verbose = false
    t.warning = false
  end
end

task :easy_three_task do
  Rake::TestTask.new('easy_three') do |t|
    t.libs << "easy/three/test"
    t.test_files = FileList['easy/three/test/*_test.rb']
    t.verbose = false
    t.warning = false
  end
end

task :medium_one_task do
  Rake::TestTask.new('medium_one') do |t|
    t.libs << "medium/one/test"
    t.test_files = FileList['medium/one/test/*_test.rb']
    t.verbose = false
    t.warning = false
  end
end

task :hard_one_task do
  Rake::TestTask.new('hard_one') do |t|
    t.libs << "hard/one/test"
    t.test_files = FileList['hard/one/test/*_test.rb']
    t.verbose = false
    t.warning = false
  end
end

task :easy_one do
  Rake::Task['easy_one_task'].invoke
end

task :easy_two do
  Rake::Task['easy_two_task'].invoke
end

task :easy_three do
  Rake::Task['easy_three_task'].invoke
end

task :medium_one do
  Rake::Task['medium_one_task'].invoke
end

task :hard_one do
  Rake::Task['hard_one_task'].invoke
end
