  WelcomeMsg: "Welcome to the Mortgage Calculator"
  InvalidNumMsg: "Hmm... that doesn't look like a valid number"
  LoanAmtMsg: |
    Enter your loan amount.
    You must use commas for numbers greater than 999.
    Decimals must have at least one digit left of the decimal pont.
    What is your loan amount?