  InterestAmtMsg: |
    Enter your interest amount.
    The number must be an annual interest rate number.
    Enter a number representing the percent interest you desire.
    Conversion to decimal will be done by the program.
    There must be at least one digit to the left of the decimal point.
    There cannot be more than two digits to the left of the decimal point.
    Zero and negative rates are not allowed.
    What is your interest rate?
  LoanAmtMsg: |
    Enter your loan amount.
    You must use commas for numbers greater than 999.
    Decimals must have at least one digit left of the decimal pont.
    Zero and negative numbers are not allowed.
    What is your loan amount?
  LoanDurationMsg: |
    Enter your loan duration in months.
    No decimal numbers are allowed.
    Neither are negative numbers or zero.
    What is the loan duration in months?
  WelcomeMsg: "Welcome to the Mortgage Calculator"
  InvalidLoanMsg: "Hmm... that doesn't look like a valid loan amount entry"
  InvalidInterestMsg: "Hmm... that doesn't look like a valid interest rate entry"
  InvalidLoanDurationMsg: "Hmm... that doesn't look like a valid loan duration entry"